management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - "*"
          - "gateway"
  endpoint:
    gateway:
      enabled: true
spring:
  application:
    name: summer-gateway
  profiles:
    active:
      - dev
      - database