management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - "*"
          - "gateway"
  endpoint:
    gateway:
      enabled: true
spring:
  application:
    name: summer-gateway
  profiles:
    active:
      - dev
      - db
#  cloud:
#    gateway:
#      routes:
#        - id: test-summer-filter
#          predicates:
#            - Path=/manager/admin/menu/tree/navigate
#          order: 0
#          uri: lb://summer-manager
#          filters:
#            - AddRequestUserInfo=testkks
